### ISSUE TITLE
Can't run webpack-dev-server

### ISSUE THREAD

**Issue by charlesh88** [VWoeltjen/openmct-map#2]
Followed all instructions in README.md, but trying to run `webpack-dev-server` it throws this error:
> The CLI moved into a separate package: webpack-cli.
Please install 'webpack-cli' in addition to webpack itself to use the CLI.
-> When using npm: npm install webpack-cli -D
-> When using yarn: yarn add webpack-cli -D
module.js:549
    throw err;
    ^
Error: Cannot find module 'webpack-cli/bin/config-yargs'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/chacskay/.nvm/versions/node/v8.10.0/lib/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)

I installed the webpack-cli as directed with apparent success messaging, but every subsequent run of `webpack-dev-server` throws the same error as noted above. I am using nvm v8.10.0.

Help appreciated.

**Comment by charlesh88** [comment]
Worked with Andrew on this: solution was to install webpack with -g instead of -D.
